# Site settings
email: "boris@rorsvort.com"
baseurl: ""
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics: UA-2826331-18

# SEO settings
title: Boris Rorsvort — Ux Designer and full stack Rails / Js developper
description: Web applications, team processes & teach code. Startup McGyver based in Brussels, Belgium
url: https://www.rorsvort.com
twitter_username: borisrorsvort

# Profile settings
name: Boris Rorsvort

# Build settings
# include: ["_categories", "_projects"]
exclude: ["Gemfile", "Gemfile.lock"]
markdown: kramdown

collections:
  projects:

defaults:
  - scope:
      type: projects
    values:
      categories: []
      image: ""
  - scope:
      type: posts
    values:
      categories: ["blog"]

# Sass
sass:
  sass_dir: _sass
  style: compressed

# Gems
plugins: [jekyll-paginate, jekyll-sitemap, jekyll-autoprefixer]
