---
new_page_extension: md
auto_deploy: false
admin_path: "/admin"
webhook_url:
sections:
  - type: jekyll-pages
    label: Pages
    create: all
  - type: directory
    path: _projects
    label: Projects
    create: all
    match: "**/*"
  - type: jekyll-posts
    label: Posts
    create: all
upload_dir: assets/images
public_path: "{{ site.baseurl }}/assets/images"
front_matter_path: "/assets/images"
use_front_matter_path: true
file_template: ":filename:"
instant_preview: true
build:
  preview_env:
    - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
  instant_preview_command:
    bundle exec jekyll serve --drafts --unpublished --future
    --port 8080 --host 0.0.0.0 -d _site
  preview_command: bundle exec jekyll build --drafts --unpublished --future -d _site
